# Generated by Django 5.2.17 on 2026-10-01 11:26

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import docintel.apps.core.ids
import docintel.apps.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'core_company',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'core_user',
            },
            managers=[
                ('objects', docintel.apps.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('reviewer', 'Reviewer'), ('member', 'Member')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_membership',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='membership_company_user')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ToolPermission',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('reviewer', 'Reviewer'), ('member', 'Member')], max_length=20)),
                ('tool_slug', models.CharField(max_length=40)),
                ('actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_tool_permission',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['company', 'tool_slug'], name='toolperm_company_tool')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('role', ''), ('user__isnull', False)), models.Q(('user__isnull', True), models.Q(('role', ''), _negated=True)), _connector='OR'), name='toolperm_user_xor_role'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('company', 'user', 'tool_slug'), name='toolperm_user_tool'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('company', 'role', 'tool_slug'), name='toolperm_role_tool')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
