# Generated by Django 5.2.17 on 2026-10-01 11:26

import django.db.models.deletion
import django.db.models.manager
import docintel.apps.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=80)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('idempotency_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('dead_letter', 'Dead letter')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('last_error', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'db_table': 'sync_event',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SyncRule',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=80)),
                ('destination_url', models.URLField(max_length=500)),
                ('signing_secret', models.CharField(max_length=200)),
                ('field_mapping', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'db_table': 'sync_rule',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SyncDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.PositiveIntegerField()),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sync.syncevent')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sync.syncrule')),
            ],
            options={
                'db_table': 'sync_delivery_log',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='syncevent',
            index=models.Index(fields=['status', 'next_attempt_at'], name='sync_event_due'),
        ),
        migrations.AddConstraint(
            model_name='syncevent',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='sync_event_idempotency'),
        ),
        migrations.AddIndex(
            model_name='syncrule',
            index=models.Index(fields=['company', 'event_type', 'is_active'], name='sync_rule_lookup'),
        ),
        migrations.AddIndex(
            model_name='syncdeliverylog',
            index=models.Index(fields=['event', 'rule', 'succeeded'], name='sync_delivery_success'),
        ),
    ]
