# Generated by Django 5.2.17 on 2026-10-01 11:26

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.manager
import docintel.apps.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # gin_trgm_ops on Vendor.normalized_name requires this extension
        # before the model index is created. Empty tables do not need
        # CREATE INDEX CONCURRENTLY; that form belongs in a later migration
        # if this index is added to a populated table (atomic = False).
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=40)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('default_gl_code', models.CharField(blank=True, max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'db_table': 'documents_vendor',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_key', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_upload', 'Pending upload'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('extracted', 'Extracted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending_upload', max_length=20)),
                ('textract_job_id', models.CharField(blank=True, max_length=80)),
                ('failure_reason', models.CharField(blank=True, max_length=80)),
                ('vendor_match_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('raw_response_s3_key', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.vendor')),
            ],
            options={
                'db_table': 'documents_document',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.document')),
            ],
            options={
                'db_table': 'documents_event',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['document', 'created_at'], name='doc_event_timeline')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80)),
                ('value', models.TextField(blank=True)),
                ('normalized_value', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('textract', 'Textract'), ('human', 'Human')], default='textract', max_length=20)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_corrections', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.document')),
            ],
            options={
                'db_table': 'documents_extracted_field',
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('document', 'key'), name='field_document_key')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.UUIDField(default=docintel.apps.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='documents.document')),
            ],
            options={
                'db_table': 'documents_line_item',
                'ordering': ['position'],
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('document', 'position'), name='line_document_position')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_name'], name='vendor_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_name'), name='vendor_company_norm_name'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'status', 'created_at'], name='doc_co_status_created'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'invoice_number'], name='doc_co_invoice_no'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'total'], name='doc_co_total'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'invoice_date'], name='doc_co_invoice_date'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('status', 'processing')), fields=['updated_at'], name='doc_processing_poll'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('status', 'needs_review')), fields=['company', 'created_at'], name='doc_review_queue'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending_upload', 'uploaded', 'processing', 'needs_review', 'extracted', 'approved', 'rejected', 'failed'])), name='document_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('sha256', ''), _negated=True), fields=('company', 'sha256'), name='doc_company_sha256'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('textract_job_id', ''), _negated=True), fields=('textract_job_id',), name='doc_unique_textract_job'),
        ),
    ]
